AllCops:
  Include:
    - tasks/*.rake
    - Guardfile
    - Rakefile
  Exclude:
    - puppet/**/*
    - vendor/**/*
    - spec/unit/helpers/iso_to_solr_spec.rb

AbcSize:
  Max: 20

ClassLength:
  Max: 125

CyclomaticComplexity:
  Max: 8

Encoding:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Max: 22

Metrics/ModuleLength:
  Max: 101

RescueModifier:
  Enabled: false

Style/Documentation:
  Enabled: false
