AllCops:
  Include:
    - tasks/*.rake
    - Guardfile
    - Rakefile
  Exclude:
    - puppet/**
    - vendor/**

AbcSize:
  Max: 20

ClassLength:
  Max: 125

CyclomaticComplexity:
  Max: 8

Encoding:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Max: 18

RescueModifier:
  Enabled: false
