inherit_from: rubocop-todo.yml

AllCops:
  Includes:
    - tasks/*.rake
    - Guardfile
    - Rakefile

Encoding:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Max: 15

RescueModifier:
  Enabled: false
