AllCops:
  Includes:
    - tasks/*.rake
    - Guardfile
    - Rakefile
  Excludes:
    - puppet/**
    - vendor/**

ClassLength:
  Max: 125

CyclomaticComplexity:
  Max: 8

Encoding:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Max: 18

RescueModifier:
  Enabled: false
